# This workflow will build gingerspec-starter project with Maven

name: gingerspec-starter pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Setting up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: maven

    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2

    - name: Build with Maven
      run: mvn install -Dmaven.test.skip=true

    - name: Update local archetype catalog
      run: mvn archetype:update-local-catalog && mvn archetype:crawl

    - name: Generating a new project based on local archetype and performing a dry-run
      run: |
        mkdir test
        cd test/
        yes | mvn archetype:generate -DarchetypeCatalog=local -DarchetypeGroupId=com.github.josefd8 -DarchetypeArtifactId=gingerspec-starter -DgroupId=com.mydomain -Dversion=1.0-SNAPSHOT -DartifactId=myproject
        cd myproject/
        mvn verify -Dcucumber.execution.dry-run=true


